
const svgsNames = [
 'Adhering Hull',
 'arrow-clockwise',
 'arrow-down-short',
 'arrow-down',
 'arrow-left',
 'arrow-right',
 'arrows-expand-vertical',
 'Aspect Ratio',
 'BadSelected',
 'box-arrow-in-down',
 'box-arrow-in-right',
 'box-arrow-left',
 'caret-down-fill',
 'check2',
 'chevron-bar-down',
 'chevron-double-left',
 'chevron-double-right',
 'chevron-down',
 'chevron-left',
 'chevron-right',
 'circle-fill',
 'clipboard-data',
 'code-slash',
 'code',
 'Crinkle Shell',
 'crosshair',
 'Dark Stain',
 'dash',
 'disable Adhering Hull',
 'disable Aspect Ratio',
 'disable Crinkle Shell',
 'disable Dark Stain',
 'disable Half Split Shell',
 'disable Kernel',
 'disable Light Stain',
 'disable Mold',
 'disable Non Extra Split Shell',
 'disable Non Extra Split Shelll',
 'disable Non Split Shell',
 'disable notFound',
 'disable Rancid',
 'disable Reject By Length',
 'disable Reject By Width',
 'disable Yellow Stain',
 'downArrow',
 'extendedLine',
 'eye-line',
 'eye-slash',
 'file-earmark-plus',
 'filter',
 'folder-fill',
 'GoodSelected',
 'Half Split Shell',
 'horizontalLine',
 'image',
 'journal-text',
 'Kernel',
 'layers-fill',
 'Light Stain',
 'list',
 'loadingAnimation',
 'Mold',
 'Non Extra Split Shelll',
 'Non Split Shell',
 'notFound',
 'OK',
 'pause-fill',
 'pencil-fill',
 'play-fill',
 'plus-circle',
 'plus-lg',
 'plus',
 'Rancid',
 'Reject By Length',
 'Reject By Width',
 'three-dots',
 'Total',
 'Trash',
 'trash3-fill',
 'trash3',
 'Unknown',
 'upArrow',
 'verticalLine',
 'wrench-adjustable-circle',
 'x-lg',
 'x',
 'Yellow Stain',
] as const

export type SvgsNames = typeof svgsNames[number];