// const CHART_THEME = {

// }
//         {
//             label: "توزیع پایین بار خوب",
//             backgroundColor: "rgba(0, 199, 129,0.2)",
//             borderColor: "rgb(0, 199, 129)",
//             borderDash: [1,2],
//             borderDashOffset: 2,
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         },
//         {
//             label: "نمودار بار خوب",
//             backgroundColor: "rgba(0, 199, 129,0.2)",
//             borderColor: "rgb(0, 199, 129)",
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         },
//         {
//             label: "توزیع بالا بار خوب",
//             backgroundColor: "rgba(0, 199, 129,0.2)",
//             borderColor: "rgb(0, 199, 129)",
//             borderDash: [1,2],
//             borderDashOffset: 2,
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         },
//         {
//             label: "توزیع پایین بار بد",
//             backgroundColor: "rgba(255, 64, 64, 0.2)",
//             borderColor: "rgb(255, 64, 64)",
//             borderDash: [1,2],
//             borderDashOffset: 2,
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         },
//         {
//             label: "نمودار بار بد",
//             backgroundColor: "rgba(255, 64, 64, 0.2)",
//             borderColor: "rgb(255, 64, 64)",
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         },
//         {
//             label: "توزیع بالا بار بد",
//             backgroundColor: "rgba(255, 64, 64, 0.2)",
//             borderColor: "rgb(255, 64, 64)",
//             borderDash: [1,2],
//             borderDashOffset: 2,
//             borderWidth: 2,
//             pointStyle: false,
//             hoverRadius: 0,
//             pointHoverRadius: 0,
//             hitRadius: 0,
//             pointHitRadius: 0,
//             pointRadius: 0,
//         }]